### ISSUE TITLE
subscribeToInAppMessage not work because sendDeviceEventWithName is deprecated  

### ISSUE THREAD

**Issue by zrg-team** [Appboy/appboy-react-sdk#167]
```
- (ABKInAppMessageDisplayChoice) beforeInAppMessageDisplayed:(ABKInAppMessage *)inAppMessage {
  NSData *inAppMessageData = [inAppMessage serializeToData];
  NSString *inAppMessageString = [[NSString alloc] initWithData:inAppMessageData encoding:NSUTF8StringEncoding];
  NSDictionary *arguments = @{
    @"inAppMessage" : inAppMessageString
  };
  // Send to JavaScript
  [self.bridge.eventDispatcher
             sendDeviceEventWithName:@"inAppMessageReceived"
             body:arguments];
  // Note: return ABKDiscardInAppMessage if you would like
  // to prevent the Braze SDK from displaying the message natively.
  return ABKDisplayInAppMessageNow;
}
```

**Comment by wesleyorbin** [comment]
Hi @zrg-team. Unless you have a need to customize when to show in-app messages through the Braze UI, I recommend using the `subscribeToInAppMessage` method introduced in 1.37.0 rather than add your own native code. Otherwise, you should subclass `RCTEventEmitter` in the class that contains your `beforeInAppMessageDisplayed` code in order to send events to the Javascript bridge. I've filed a ticket to update our documentation to recommend its usage when customizing integration.
