### ISSUE TITLE
Does 1.38.0 supports latest version of RN ie 0.70 (old arch)?

### ISSUE THREAD

**Issue by Kailash23** [Appboy/appboy-react-sdk#170]
Please let me know what is the latest RN version that braze supports?

**Comment by wesleyorbin** [comment]
Hi @Kailash23. Our SDK is not tied to a specific version of React Native. Are you have any specific issues when integrating with 0.70?

**Comment by cam-shaw** [comment]
@wesleyorbin Am getting a signing error when trying to use v1.38.1 with React Native 0.70
Possible there is an issue on my side - are you able to replicate?
![Screen Shot 2022-09-13 at 9 53 39 am](https://user-images.githubusercontent.com/6579750/189778411-9dd72b2b-b804-4f93-a972-8f8ca6e0329d.png)

**Comment by Kailash23** [comment]
> 

Yes @wesleyorbin 
I faced this [issue](https://github.com/react-native-push-notification/ios/issues/76#issuecomment-655692104).

Assigning to 'id<UNUserNotificationCenterDelegate> _Nullable' from incompatible type 'AppDelegate *const __strong'

It started working after this fix in `AppDeligate.h`

**Comment by wesleyorbin** [comment]
@cam-shaw This appears to be an issue with CocoaPods. [This fix](https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1201464693) should resolve these errors. 

I'm going to close out the issue since these errors do not appear to be related to the SDK, but feel free to reopen or file a new issue should any others arise.
