### ISSUE TITLE
Xcode 14 Code Signing

### ISSUE THREAD

**Issue by cam-shaw** [Appboy/appboy-react-sdk#181]
![image](https://user-images.githubusercontent.com/6579750/195760457-3768509d-96bf-4315-9dff-4d98bb40dc3f.png)

RN updated to turn off code signing for their packages to resolve this issue, it would be great if the Braze team could also do the same 🙏 
https://github.com/facebook/react-native/commit/967de03f304404ac8817936da37ca39514a09e33

Previously mentioned in here: https://github.com/Appboy/appboy-react-sdk/issues/170
This is not an issue with RN but is instead an issue with a change in Xcode 14.

Workarounds have been [suggested](https://github.com/CocoaPods/CocoaPods/issues/11402) to disable Code Signing on everything but that's not a great solution.

**Comment by cam-shaw** [comment]
@wesleyorbin bringing your attention to this again. Would be awesome if we could get to a solution in the package for this.

**Comment by KraljSamo** [comment]
Also need this desperately.

**Comment by wesleyorbin** [comment]
As of right now, we recommend using the suggested workaround in your post_install script. It does not appear that there is any way for us to build a workround directly into the package since podspecs do not support post_install scripts. You can specify that code signing should only be turned off for our native iOS SDK rather than turning it off for everything.

```ruby
installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
    if pod_name.to_s == 'Appboy-iOS-SDK'
        target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
            resource_bundle_target.build_configurations.each do |config|
                config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            end
        end
    end
end
```

If you don't feel comfortable turning off code signing, I would suggest trying this workaround which should add the development team automatically: https://github.com/bitrise-steplib/steps-xcode-archive/issues/299#issuecomment-1255652117

**Comment by wesleyorbin** [comment]
Closing this out since there's nothing we can do on our side at this time

**Comment by novellizator** [comment]
On XCode 14 it fixes the imminent issue, but still makes you unable launch on a physical device due to: 

> A valid provisioning profile for this executable was not found.
> Domain: com.apple.dt.MobileDeviceErrorDomain
> Code: -402620395

Also documented https://developer.apple.com/forums/thread/722892 . Anyone facign similar problems?

**Comment by joepatosh** [comment]
For anyone still facing this problem, it seems upgrading to cocoapods >= 1.12.0 can fix it. I had this problem today and on xcode 14.1 and upgrading to cocoapods 1.12 fixed the problem.

See here: https://github.com/CocoaPods/CocoaPods/pull/11723
