### ISSUE TITLE
Android support for customer feedback

### ISSUE THREAD

**Issue by zevmo** [Appboy/appboy-react-sdk#21]
We currently use the iOS process for allowing customer feedback. We would love to be able to do the same on Android using the React Native bridge.

**Comment by tiffanylu** [comment]
Hi @zevmo, thanks for the feedback! Our team will investigate adding support and follow up with more details once we've specced this out further. To clarify, are you currently using the `launchFeedback()` functionality on iOS? 

Best,
Tiff

**Comment by tiffanylu** [comment]
Hi @zevmo,

Thanks for filing this issue.  Unfortunately, adding Android Feedback support to our React Native bridge would be nontrivial since our Android Feedback UI only exists as a Fragment (as opposed to a standalone Activity). We do expose a `submitFeedback()` function for submitting feedback to Appboy which would be compatible with any React Native UI - however, you would have to build the custom UI on your end.

Let us know how this alternative sounds on your end.

Thanks!
Tiff
