### ISSUE TITLE
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. 

### ISSUE THREAD

**Issue by vitorreis** [Appboy/appboy-react-sdk#49]
>WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
>It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Do you guys have this upgrade in the roadmap?

**Comment by radixdev** [comment]
Hello @vitorreis ,

Thanks for filing this issue. The fix for this issue has been implemented for a future release of the [base android SDK](https://github.com/Appboy/appboy-android-sdk). That release will then be added into the react SDK. One of our dependencies was using `compile` and we had to update it to fix the warning.

Thanks,
Julian

**Comment by Bucimis** [comment]
@vitorreis this is now fixed, thanks!
