### ISSUE TITLE
Silent Push Notifications

### ISSUE THREAD

**Issue by simonso-nzme** [Appboy/appboy-react-sdk#79]
Hi,

I have been recommended by the support team on retrieving the current user's custom attributes via silent push notifications.
Basically attaching the KVP to the silent notifications

Couple of issues I am facing:

1) I have been unsuccessful (on iOS at least) -The native on receive event was not triggered with content-available flag on but it does trigger on normal notifications with content-available flag unchecked.

2) How do I pass the KVP from native (userInfo) to the react-native side? I couldn't find anything on the example and documentation.

Thanks
Simon

**Comment by Bucimis** [comment]
Hi @simonso-nzme 

1) You should ensure you've followed our complete iOS native push integration instructions. Depending on the state of the app (not running, backgrounded, foregrounded, etc) different delegate methods may receive the push payload.
2) Unfortunately we don't have documentation around this at the moment. Native push payloads need to be sent to the javascript layer using a custom React Native Bridge. We've added a backlog item for us to improve support here, either through documentation or new bridge methods, but it will take us some time to get there.

High level comment on the use case - since the SDK is write-only and silent push is tricky to set up/asynchronous/not 100% reliable, we recommend keeping track of attributes needed by the app locally on the device (as well as sending them to Braze for segmentation purposes) rather than trying to read them back from Braze using silent push.
