### ISSUE TITLE
startWithApiKey() is not available to consume as per inline comments

### ISSUE THREAD

**Issue by sahanatroam** [Appboy/appboy-react-sdk#83]
Hi @wesleyorbin

```
/**
 * Enables the Braze SDK after a previous call to disableSDK().
 * On iOS, the SDK will be enabled only after a subsequent call to startWithApiKey().
 */
```

We're trying to feature toggle the SDK by using enableSDK() and disableSDK(), but seems like a method mentioned in the code is missing.

https://github.com/Appboy/appboy-react-sdk/blob/master/index.d.ts#L474

**Comment by wesleyorbin** [comment]
Hi @sahanatroam! Thanks for reaching out.

This method was intentionally left out of the Javascript interface because it should instead be called in the iOS app's AppDelegate (as seen in [the iOS SDK documentation](https://appboy.github.io/appboy-ios-sdk/docs/interface_appboy.html#afd911d60dfe7e5361afbfb364f5d20f9)). 

You can see an example of this in the sample project: https://github.com/Appboy/appboy-react-sdk/blob/master/AppboyProject/ios/AppboyProject/AppDelegate.m#L24.

We'll make a note to improve our documentation around this in the next release.
