### ISSUE TITLE
Ask for Push Notifications Permission

### ISSUE THREAD

**Issue by isnotahippy** [Appboy/appboy-react-sdk#95]
Maybe I have missed this in the docs, please correct me if so. It seems like the RN library has no method to trigger the Push Notifications permission request - which is a feature in OneSignal for example. This leaves us only able to request the permission from the native side of our app or write our own bridged method somewhere for this - limiting the ability for us to choose when to ask for push permission.

If this doesn't exist could we request the feature or I can look at raising a PR to add one?

**Comment by Bucimis** [comment]
Hey @isnotahippy, as you gathered, right now push is handled 100% natively on both platforms. It would be great to see a PR to see how you would want something like this shaped, otherwise I'd be happy to pass this along as a feature request. It's something we'd definitely like to build at some point

**Comment by Bucimis** [comment]
Hey @chas-ps, thanks for the extensive write-up. You can definitely handle registering and permissioning from JS - what matters most is that ultimately, the received push token is passed to Braze through `[[Appboy sharedInstance] registerDeviceToken:deviceToken];` and that various delegates for receiving push (e.g. `didReceiveRemoteNotification`) are active and working. This should be the case as long as the `UNUserNotificationCenter` delegate, set in `center.delegate = self;` points to the right class. 

As for `pushAuthorizationFromUserNotificationCenter:granted`, your intuition is right. It's helpful for getting the updated permission status down to the Braze SDK as soon as possible but isn't strictly speaking required.

Let us know how your testing goes!

**Comment by chas-ps** [comment]
@Bucimis awesome thanks for the info! To follow up we've been testing for a week or so - no problems so far

**Comment by lustig-bakkt** [comment]
@chas-ps you're the man for this write up. Implementing this today when I get back to work.

@Bucimis Highly recommend this at least goes into the docs and eventually into the SDK itself. Non-hobby projects will generally not be okay to request any permissions on startup due to the poor user experience and so this behavior is expected to be out of the box both by developers and user alike.

**Comment by scgough** [comment]
@chas-ps excellent work on this. Your notes were really helpful. I've just got this up and running using `react-native-permissions` as you suggested and initial tests work well!
